version: 0.2
env:
  parameter-store:
    REACT_APP_BASE_API_DOMAIN: "REACT-APP-BASE-API-DOMAIN"
    AWS_ACCOUNT_ID: "ENVIRONMENT_AWS_ACCOUNT_ID"
phases: 
  install:
    runtime-versions:
        docker: 18     
    commands: 
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build: 
    commands: 
    - echo Logging in to Amazon ECR.... 
    - aws --version
    - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # update the following line with the name of your own ECR repository
      - echo "PORT=5000" > .env
      - echo "REACT_APP_BASE_API_DOMAIN=${REACT_APP_BASE_API_DOMAIN}" >> .env
      - docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/node:18-alpine3.15
      - docker tag ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/node:18-alpine3.15 node:18-alpine3.15

      - docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/nginx:latest
      - docker tag ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/nginx:latest nginx:latest

      - docker build -t my_app:latest .
      - container_id=$(docker run -it --rm --detach my_app)
      - docker cp $container_id:/usr/share/nginx/html build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build